## SALES DATA ANALYSIS

## Business Problem

The retail company is preparing its monthly sales performance report, but the raw sales data contains missing values, duplicate records, inconsistent formats, incorrect data types, invalid numerical values, and potentially incorrect Sales and Profit values. If these issues are not resolved before analysis, management may make decisions using inaccurate revenue, profitability, product, regional, and salesperson information. Your task is to act as a Data Analyst and convert the raw sales file into a reliable, consistent, and analysis-ready dataset that can be safely used for reporting and future EDA.

## Import Libraries

In [1]:
pip install numpy pandas matplotlib seaborn

Requirement already satisfied: numpy in .\anaconda3\Lib\site-packages (2.4.6)
Requirement already satisfied: pandas in .\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: matplotlib in .\anaconda3\Lib\site-packages (3.11.0)
Requirement already satisfied: seaborn in .\anaconda3\Lib\site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in .\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in .\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in .\anaconda3\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\anaconda3\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\anaconda3\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in .\anaconda3\Lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in .\anaconda3\Lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=9 in .\anaconda3\Lib\site-packages (from matplotlib) (12.3.0)
Requirement already satisfied: pyparsing>=3 in .\anaconda3\Lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in .\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

## Import Modules

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

##  1. Data Loading & Initial Inspection

In [3]:
df = pd.read_csv("Sales Data Cleaning Task.csv")
print(df.shape)
print(df.columns)
print(df.head())
print(df.info())
print(df.dtypes)

(120, 11)
Index(['Order_ID', 'Order_Date', 'Region', 'Product', 'Category', 'Quantity',
       'Unit_Price', 'Discount', 'Sales', 'Profit', 'Salesperson'],
      dtype='str')
  Order_ID  Order_Date Region     Product     Category Quantity Unit_Price  \
0    S0001  2026-01-27  North  Smartphone  Electronics      1.0    28000.0
1    S0002  2026-06-04  North      Laptop  Electronics      1.0    55000.0
2    S0003  2026-01-02  South      Tablet  Electronics      4.0    22000.0
3    S0004  2026-03-28  North       Mouse  Accessories      5.0      400.0
4    S0005  2026-01-12   West      Tablet  Electronics      2.0    22000.0

   Discount    Sales   Profit Salesperson
0      0.05  26600.0  3137.36       Vijay
1      0.05  52250.0  6246.61       Divya
2      0.20  70400.0  8961.39       Vijay
3      0.05   1900.0   461.18       Priya
4      0.10  39600.0  7232.28       Priya
<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Order_ID     120 non-null    str
 1   Order_Date   119 non-null    str
 2   Region       118 non-null    str
 3   Product      119 non-null    str
 4   Category     120 non-null    str
 5   Quantity     119 non-null    str
 6   Unit_Price   119 non-null    str
 7   Discount     120 non-null    float64
 8   Sales        119 non-null    float64
 9   Profit       119 non-null    float64
 10  Salesperson  118 non-null    str
dtypes: float64(3), str(8)
memory usage: 16.6 KB
None
Order_ID           str
Order_Date         str
Region             str
Product            str
Category           str
Quantity           str
Unit_Price         str
Discount       float64
Sales          float64
Profit         float64
Salesperson        str
dtype: object

## 2. Missing Values & Blank Data

In [12]:
df.isnull().sum()

Order_ID       0
Order_Date     1
Region         2
Product        1
Category       0
Quantity       1
Unit_Price     1
Discount       0
Sales          1
Profit         1
Salesperson    2
dtype: int64

In [13]:
df.isnull().sum()/df.shape[0]*100

Order_ID       0.000000
Order_Date     0.833333
Region         1.666667
Product        0.833333
Category       0.000000
Quantity       0.833333
Unit_Price     0.833333
Discount       0.000000
Sales          0.833333
Profit         0.833333
Salesperson    1.666667
dtype: float64

## 3. Duplicate Records & Order IDs

In [14]:
df.duplicated().sum()

np.int64(2)

In [15]:
df[df.duplicated(keep=False)]

,Order_ID,Order_Date,Region,Product,Category,Quantity,Unit_Price,Discount,Sales,Profit,Salesperson
20,S0021,2026-05-22,South,Monitor,Electronics,4.0,9000.0,0.1,32400.0,2707.86,Divya
45,S0046,2026-02-26,South,Headphones,Accessories,2.0,3200.0,0.0,6400.0,1446.15,Meena
115,S0021,2026-05-22,South,Monitor,Electronics,4.0,9000.0,0.1,32400.0,2707.86,Divya
119,S0046,2026-02-26,South,Headphones,Accessories,2.0,3200.0,0.0,6400.0,1446.15,Meena

In [30]:
df = df.drop_duplicates()

In [31]:
df.duplicated().sum()

np.int64(0)

## 4. Data Type & Format Correction

In [17]:
print(df.dtypes)

Order_ID           str
Order_Date         str
Region             str
Product            str
Category           str
Quantity           str
Unit_Price         str
Discount       float64
Sales          float64
Profit         float64
Salesperson        str
dtype: object

1. Convert Quantity to numeric

In [67]:
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')

2. Convert Unit_Price to numeric

In [68]:
df['Unit_Price'] = df['Unit_Price'].astype(str).str.extract(r'(\d+\.?\d*)')[0].astype(float)

3. Convert Discount, Sales and Profit

In [69]:
df[['Discount','Sales','Profit']] = df[['Discount','Sales','Profit']].apply(pd.to_numeric, errors='coerce')

4. Convert Order_Date

In [70]:
df['Order_Date'] = pd.to_datetime(df['Order_Date'], errors='coerce')

In [71]:
df.dtypes

Order_ID                  str
Order_Date     datetime64[us]
Region                    str
Product                   str
Category                  str
Quantity              float64
Unit_Price            float64
Discount              float64
Sales                 float64
Profit                float64
Salesperson               str
dtype: object

## 5. Text Standardization

In [18]:
for col in ['Region', 'Product', 'Category', 'Salesperson']:
    print(col, df[col].dropna().unique())

Region <ArrowStringArray>
['North', 'South', 'West', 'East', ' south ', 'NORTH', 'west']
Length: 7, dtype: str
Product <ArrowStringArray>
[   'Smartphone',        'Laptop',        'Tablet',         'Mouse',
      'Keyboard',       'Monitor',    'Smartwatch',    'Headphones',
      ' laptop ', 'Not Available']
Length: 10, dtype: str
Category <ArrowStringArray>
['Electronics', 'Accessories', 'Wearables', 'electronics']
Length: 4, dtype: str
Salesperson <ArrowStringArray>
[  'Vijay',   'Divya',   'Priya',   'Rahul',   'Sneha', 'Karthik',    'Arun',
   'Meena', ' priya ']
Length: 9, dtype: str

In [33]:
for col in ['Region', 'Product', 'Category', 'Salesperson']:
    df[col] = df[col].str.strip().str.title()

In [34]:
for col in ['Region', 'Product', 'Category', 'Salesperson']:
    print(col, df[col].dropna().unique())

Region <ArrowStringArray>
['North', 'South', 'West', 'East']
Length: 4, dtype: str
Product <ArrowStringArray>
[   'Smartphone',        'Laptop',        'Tablet',         'Mouse',
      'Keyboard',       'Monitor',    'Smartwatch',    'Headphones',
 'Not Available']
Length: 9, dtype: str
Category <ArrowStringArray>
['Electronics', 'Accessories', 'Wearables']
Length: 3, dtype: str
Salesperson <ArrowStringArray>
['Vijay', 'Divya', 'Priya', 'Rahul', 'Sneha', 'Karthik', 'Arun', 'Meena']
Length: 8, dtype: str

## 6. Invalid Value Detection

In [ ]:
CLEANED QUANTITY

In [37]:
df.loc[df['Order_ID'] == 'S0013', 'Quantity'] = 5

In [38]:
df.loc[df['Order_ID'] == 'S0037', 'Quantity'] = 3

INVALID QUANTITY

In [40]:
df.loc[df['Order_ID'] == 'S0032', 'Quantity'] = 8

CLEAN UNIT PRICE

In [72]:
cleaned_df['Unit_Price'] = cleaned_df['Unit_Price'].astype(str).str.extract(r'(-?\d+\.?\d*)')[0]
cleaned_df['Unit_Price'] = pd.to_numeric(cleaned_df['Unit_Price'], errors='coerce')

In [50]:
df.loc[df['Order_ID'] == 'S0055', 'Unit_Price'] = 700

In [ ]:
FIX DISCOUNT

In [51]:
df.loc[df['Order_ID'] == 'S0077', 'Discount'] = np.nan

MISSING QUANTITY

In [73]:
df.loc[df['Order_ID'] == 'S0030', 'Quantity'] = 7

## 7. Business Rule Validation

FILL MISSING UNIT PRICE

In [53]:
df.loc[df['Order_ID'] == 'S0045', 'Unit_Price'] = 15000

FILL MISSING SALES

In [54]:
df.loc[df['Order_ID'] == 'S0058', 'Sales'] = 230400

DATE CONVERSION

In [56]:
df['Order_Date'] = df['Order_Date'].replace('not available', np.nan)

In [59]:
df['Order_Date'] = df['Order_Date'].fillna(pd.Timestamp('2026-01-01'))

In [64]:
df['Region'] = df['Region'].fillna('Unknown')
df['Product'] = df['Product'].fillna('Unknown')
df['Discount'] = df['Discount'].fillna(0)
df.loc[df['Order_ID'] == 'S0058', 'Sales'] = 230400
df['Profit'] = df['Profit'].fillna(0)
df['Salesperson'] = df['Salesperson'].fillna('Unknown')

## 8. Create the Cleaned Dataset

In [74]:
cleaned_df = df.copy()

## 9. Final Data Quality Validation

In [75]:
cleaned_df.isnull().sum()

Order_ID       0
Order_Date     0
Region         0
Product        0
Category       0
Quantity       0
Unit_Price     0
Discount       0
Sales          0
Profit         0
Salesperson    0
dtype: int64

In [76]:
cleaned_df.duplicated().sum()

np.int64(0)

In [77]:
cleaned_df.duplicated().sum()

np.int64(0)

In [78]:
cleaned_df.dtypes

Order_ID                  str
Order_Date     datetime64[us]
Region                    str
Product                   str
Category                  str
Quantity              float64
Unit_Price            float64
Discount              float64
Sales                 float64
Profit                float64
Salesperson               str
dtype: object

In [79]:
cleaned_df['Category'].unique()

<ArrowStringArray>
['Electronics', 'Accessories', 'Wearables']
Length: 3, dtype: str

In [80]:
cleaned_df['Region'].unique()

<ArrowStringArray>
['North', 'South', 'West', 'East', 'Unknown']
Length: 5, dtype: str

## 10. Export & Document the Result

In [82]:
cleaned_df.to_csv("Sales Data Cleaned.csv", index=False)

In [83]:
cleaned_df.shape

(118, 11)

In [84]:
cleaned_df.head()

,Order_ID,Order_Date,Region,Product,Category,Quantity,Unit_Price,Discount,Sales,Profit,Salesperson
0,S0001,2026-01-27,North,Smartphone,Electronics,1.0,28000.0,0.05,26600.0,3137.36,Vijay
1,S0002,2026-06-04,North,Laptop,Electronics,1.0,55000.0,0.05,52250.0,6246.61,Divya
2,S0003,2026-01-02,South,Tablet,Electronics,4.0,22000.0,0.20,70400.0,8961.39,Vijay
3,S0004,2026-03-28,North,Mouse,Accessories,5.0,400.0,0.05,1900.0,461.18,Priya
4,S0005,2026-01-12,West,Tablet,Electronics,2.0,22000.0,0.10,39600.0,7232.28,Priya